### ISSUE TITLE
feature request: jump to specific line and col

### ISSUE THREAD

**Issue by LintaoAmons** [danielfalk/smart-open.nvim#83] opened 2024-08-19 10:20 UTC
When I copy from logs, it have some format like this 
a-files/abs/path.ts:28:62
And it would be great to be able to jump to that specific location by this plugin.

**Comment by danielfalk** [comment] 2024-10-15 00:28
It seems like a cool idea for a plugin, just not this plugin, unfortunately.  In fact, I think it would be cool to have a keybind that reads the format you're describing from the register and goes to the line without having to even bring up a telescope window!

I'm going to close this, but hopefully you find a good way to streamline that workflow.

**Closed by danielfalk** 2024-10-15 00:28 UTC

**Comment by LintaoAmons** [comment] 2024-10-15 10:09
Yes, can just use api to go to that file and put cursor on that spot~ 

Just trying to copy the behaviour from other editors like IDEA.

I think it has its merits since it has a consistent workflow of finding a file.

Thus don't need to remember another shortcut.

**Comment by danielfalk** [comment] 2024-10-15 15:52
OK I see what you're saying.  There's a similar request out there #73 so let's consider this a duplicate of that.
