### ISSUE TITLE
Feature request: Exit/close dialog on Control+C

### ISSUE THREAD

**Issue by f-person** [danielfalk/smart-open.nvim#41] opened 2023-08-25 09:36 UTC

**Comment by sahilsehwag** [comment] 2023-09-18 16:51
This used to work, but after recents updates in smart-open, Ctrl+c to close the telescope is not working for smart-open. This fix would be great, since this bug makes it inconsistent with Telescope general mappings. And Its inconvenient/frustrating to close smart-open window by pressing escape twice

**Comment by danielfalk** [comment] 2023-09-27 13:36
Yeah you're right.  This needs to be configurable.  I added this as a way of doing some basic buffer management within the finder.  For me it works nicely, but then I have telescope set up to close with a single escape, and I know that's not necessarily common.

Anybody want to take this on?  I can at some point, but if anyone can do so quicker and wants to contribute, I'd appreciate. 

And my apologies for the regression!  I didn't know C-c was used by anybody for quickly closing.

**Comment by tanishqmanuja** [comment] 2024-03-20 17:22
Is there a workaround for now ?

**Comment by danielfalk** [comment] 2024-03-21 14:41
If you can turn this into a PR I'd happily take it.  I've just been too busy to get to these issues, though I fully intend to return to addressing them all.

**Comment by tanishqmanuja** [comment] 2024-03-21 21:58
This is just a workaround, and can be added to users init.lua for now. Couldn't be a part of the actual plugin because the best way would be to make the plugin use the mapping from telescope's config instead of manually overwriting to ctrl + c for everyone. 

I understand maintaining open source can be difficult at times, so take your time. Great plugin overall.. really enjoying it ✨

**Comment by danielfalk** [comment] 2024-04-15 21:08
Hi, I've started a new branch 0.2.x where I have a fix for this. If you want to try it out and let me know, that would be great. I'll be updating that branch more hopefully in the near future and if it looks good, will start recommending it more broadly.

I'll close this for now, but if you want to try it out feel free to leave feedback here.

**Closed by danielfalk** 2024-04-15 21:08 UTC
Labels: help wanted

**Comment by danielfalk** [comment] 2024-04-15 21:11
Oh, and just a comment on the fix, I've just changed the default keymapping from C-c to C-w, but even that can be overridden through your own `mappings` table.  Still looking for feedback, but if this seems good, I can start documenting.

**Comment by tanishqmanuja** [comment] 2024-04-16 04:43
Sure, I will test soon... Thanks for the fix 💯
